import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Glass, Eyebrow } from "@/components/glass";
import { FileText, ScanLine, ShieldAlert, ShieldCheck, HelpCircle, Download, Calendar } from "lucide-react";
import { cn } from "@/lib/utils";
import { formatDate } from "@/lib/analysis";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [{ title: "SignalScope - Reports" }],
  }),
  component: ReportsPage,
});

interface ScanReport {
  id: string;
  file_name: string;
  verdict: "synthetic" | "authentic" | "uncertain";
  confidence: number;
  created_at: string;
}

const VERDICT_CONFIG = {
  synthetic: {
    label: "AI-Generated",
    icon: ShieldAlert,
    bg: "bg-red-500/10",
    text: "text-red-400",
    border: "border-red-500/20",
    dot: "bg-red-400",
  },
  authentic: {
    label: "Likely Authentic",
    icon: ShieldCheck,
    bg: "bg-green-500/10",
    text: "text-green-400",
    border: "border-green-500/20",
    dot: "bg-green-400",
  },
  uncertain: {
    label: "Uncertain",
    icon: HelpCircle,
    bg: "bg-yellow-500/10",
    text: "text-yellow-400",
    border: "border-yellow-500/20",
    dot: "bg-yellow-400",
  },
};

function ConfidenceBar({ value, verdict }: { value: number; verdict: string }) {
  const color = verdict === "synthetic" ? "bg-red-400" : verdict === "authentic" ? "bg-green-400" : "bg-yellow-400";
  return (
    <div className="flex items-center gap-3">
      <div className="h-1.5 flex-1 rounded-full bg-white/10 overflow-hidden">
        <div
          className={cn("h-full rounded-full transition-all duration-700", color)}
          style={{ width: `${value}%` }}
        />
      </div>
      <span className="w-10 text-right text-xs font-medium text-foreground">{value.toFixed(1)}%</span>
    </div>
  );
}

function ReportCard({ report }: { report: ScanReport }) {
  const cfg = VERDICT_CONFIG[report.verdict];
  const Icon = cfg.icon;

  const downloadReport = () => {
    const text = [
      `SignalScope Forensic Report`,
      `═══════════════════════════════`,
      ``,
      `File:        ${report.file_name}`,
      `Scan ID:     ${report.id}`,
      `Date:        ${new Date(report.created_at).toLocaleString()}`,
      ``,
      `VERDICT:     ${cfg.label.toUpperCase()}`,
      `Confidence:  ${report.confidence.toFixed(1)}%`,
      ``,
      `═══════════════════════════════`,
      `Generated by SignalScope | ${new Date().toLocaleDateString()}`,
    ].join("\n");

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `signalscope-report-${report.id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Glass className="p-5">
      <div className="relative z-[3] flex flex-col gap-4 sm:flex-row sm:items-start">
        {/* Verdict icon */}
        <div className={cn("flex size-12 shrink-0 items-center justify-center rounded-xl border", cfg.bg, cfg.border)}>
          <Icon className={cn("size-6", cfg.text)} />
        </div>

        {/* Details */}
        <div className="flex-1 min-w-0 space-y-3">
          <div className="flex items-start justify-between gap-2">
            <div className="min-w-0">
              <h3 className="truncate text-[15px] font-semibold text-foreground">{report.file_name}</h3>
              <div className="mt-1 flex items-center gap-2 flex-wrap">
                <span className={cn("rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider", cfg.bg, cfg.text)}>
                  {cfg.label}
                </span>
                <span className="flex items-center gap-1 text-[11px] text-muted-foreground">
                  <Calendar className="size-3" />
                  {formatDate(report.created_at)}
                </span>
              </div>
            </div>
            <button
              onClick={downloadReport}
              title="Download report"
              className="shrink-0 flex items-center gap-1.5 rounded-md border border-border px-2.5 py-1.5 text-[11px] font-medium text-muted-foreground transition-colors hover:bg-white/5 hover:text-foreground"
            >
              <Download className="size-3" />
              Export
            </button>
          </div>

          {/* Confidence bar */}
          <div>
            <p className="mb-1.5 text-[11px] text-muted-foreground">Confidence score</p>
            <ConfidenceBar value={report.confidence} verdict={report.verdict} />
          </div>

          {/* Scan ID */}
          <p className="text-[10px] font-mono text-subtle-foreground">ID: {report.id}</p>
        </div>
      </div>
    </Glass>
  );
}

function ReportsPage() {
  const [reports, setReports] = useState<ScanReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<"all" | "synthetic" | "authentic" | "uncertain">("all");
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    async function fetchReports() {
      setLoading(true);
      const { data: { session } } = await supabase.auth.getSession();
      setIsLoggedIn(!!session);

      if (!session) { setLoading(false); return; }

      const { data, error } = await supabase
        .from("scans")
        .select("id, file_name, verdict, confidence, created_at")
        .order("created_at", { ascending: false });

      if (!error && data) {
        setReports(data as ScanReport[]);
      } else if (error && error.code !== '42P01' && error.code !== '42703') {
        console.warn("fetchReports error:", error.message);
      }
      setLoading(false);
    }
    fetchReports();
  }, []);

  const filtered = filter === "all" ? reports : reports.filter((r) => r.verdict === filter);
  const counts = {
    all: reports.length,
    synthetic: reports.filter((r) => r.verdict === "synthetic").length,
    authentic: reports.filter((r) => r.verdict === "authentic").length,
    uncertain: reports.filter((r) => r.verdict === "uncertain").length,
  };

  return (
    <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6">
      <Eyebrow>Forensic Results</Eyebrow>
      <h1 className="mt-2 text-[30px] font-semibold tracking-tight text-foreground sm:text-[36px]">
        Reports
      </h1>
      <p className="mt-2 text-[14px] text-muted-foreground">
        Every image you analyze generates a permanent report stored in your account.
      </p>

      {/* Filter tabs */}
      {reports.length > 0 && (
        <div className="mt-6 flex gap-2 flex-wrap">
          {(["all", "synthetic", "authentic", "uncertain"] as const).map((v) => (
            <button
              key={v}
              onClick={() => setFilter(v)}
              className={cn(
                "rounded-full px-3 py-1.5 text-[12px] font-medium transition-colors",
                filter === v
                  ? "bg-foreground text-background"
                  : "bg-white/5 text-muted-foreground hover:bg-white/10 hover:text-foreground"
              )}
            >
              {v === "all" ? "All" : VERDICT_CONFIG[v].label}
              <span className="ml-1.5 text-[10px] opacity-60">{counts[v]}</span>
            </button>
          ))}
        </div>
      )}

      <div className="mt-6 grid gap-4">
        {loading ? (
          [1, 2, 3].map((i) => (
            <Glass key={i} className="p-5">
              <div className="flex gap-4 animate-pulse">
                <div className="size-12 rounded-xl bg-white/10 shrink-0" />
                <div className="flex-1 space-y-2">
                  <div className="h-4 w-48 rounded bg-white/10" />
                  <div className="h-3 w-28 rounded bg-white/10" />
                  <div className="h-2 w-full rounded-full bg-white/10 mt-4" />
                </div>
              </div>
            </Glass>
          ))
        ) : filtered.length === 0 ? (
          <Glass className="p-10 text-center">
            <FileText className="mx-auto mb-4 size-10 opacity-30" />
            <p className="text-[15px] font-medium text-foreground">
              {reports.length === 0
                ? isLoggedIn ? "No reports yet" : "Sign in to view reports"
                : `No ${filter} results`}
            </p>
            <p className="mt-2 text-[13px] text-muted-foreground">
              {reports.length === 0 && isLoggedIn && "Run your first scan to generate a report."}
            </p>
            {reports.length === 0 && isLoggedIn && (
              <Link
                to="/scan"
                className="mt-5 inline-flex items-center gap-2 rounded-[999px] bg-primary px-5 py-2.5 text-[13px] font-medium text-primary-foreground transition-opacity hover:opacity-90"
              >
                <ScanLine className="size-4" /> Scan an image
              </Link>
            )}
          </Glass>
        ) : (
          filtered.map((report) => <ReportCard key={report.id} report={report} />)
        )}
      </div>
    </div>
  );
}
